[server]
enableStaticServing = true

[theme]
primaryColor = "#1A6CE7"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F7F7F7"
textColor = "#1E252F"
borderColor = "#D6DAE5"
showBorderAroundInputs = true
font = "Inter"

[[theme.fontFaces]]
url = "app/static/Inter-VariableFont_opsz,wght.ttf"
family = "Inter"
font-weight = "100 900"

